### ISSUE TITLE
When I pass a environment variable to a program loaded by callf, 

### ISSUE THREAD

**Issue by phantomcraft** [neko-para/tool#2]
When I load a library with help of callf, it loads normally:

```
user@localhost:/dev/shm/tool/tool$ LD_LIBRARY_PATH=/dev/shm/tool/tool/ ./callf /home/user/Desktop/nswizard/nswizard_lib.so echo '1'
libnswizard:71 / errno=0 / NSWIZARD_N does not defined
```

But this library (nswizard) uses environment variables, and when I try to pass them to the program, I give an error:

```
user@localhost:/dev/shm/tool/tool$ LD_LIBRARY_PATH=/dev/shm/tool/tool/ NSWIZARD_N=1 ./callf /home/user/Desktop/nswizard/nswizard_lib.so echo '1'
Load function echo from /home/user/Desktop/nswizard/nswizard_lib.so failed!
```

Any way to make the library "see" the variable(s)?

**Comment by neko-para** [comment]
As you can see in [plugin.posix.c](https://github.com/neko-para/tool/blob/master/src/plugin.posix.c), I just use dlopen and relative functions to load library. I think your problem is that the loaded library cannot get the preset environment. I think you can try writing a simple wrapper, which just set the `NSWIZARD_N`, load the library and call the function directly. This may gain some more information.
I don't think this is the problem about callf 🤣

**Comment by phantomcraft** [comment]
Ok, I will see what I can do here.
